In [3]:
import torch

In [11]:
a = torch.randint(1, 10, (3, 4))

In [12]:
a

tensor([[8, 8, 3, 9],
        [3, 1, 3, 8],
        [6, 3, 1, 9]])

In [13]:
a.chunk(2, 1)

(tensor([[8, 8],
         [3, 1],
         [6, 3]]),
 tensor([[3, 9],
         [3, 8],
         [1, 9]]))

In [26]:
b = torch.randn(3, 6, 6)
b

tensor([[[ 0.6308,  0.4781,  2.1576,  1.3261, -1.2998, -0.6536],
         [-0.4360,  0.0791,  0.3405, -0.3623,  0.1135,  1.4637],
         [ 1.3163, -0.6637,  1.4912, -1.2833, -0.6695, -1.3839],
         [ 0.8024,  0.5533,  1.0480, -0.9834, -0.4118,  0.4826],
         [-0.7365,  0.0649,  0.2887,  0.4274,  1.4250,  0.8255],
         [ 1.0499,  0.8303, -0.3787,  0.7248, -0.1515, -0.3161]],

        [[ 0.2034, -0.5167, -1.8963, -0.8965, -0.2165,  1.3446],
         [ 0.4233, -1.0409,  1.1724,  0.4128, -0.1404,  1.2276],
         [ 0.7017,  0.2702,  0.2745,  0.4467, -1.7363, -0.9114],
         [ 0.4591, -1.6639, -0.3265, -0.4321, -0.7829, -1.6865],
         [-1.4750,  0.3558,  0.4824,  0.5212, -0.6784, -0.5894],
         [-2.7914, -0.1671, -0.5346,  0.3894,  1.4930,  1.1020]],

        [[ 0.0578, -0.9207, -0.2037,  0.3218, -0.5950, -1.1804],
         [-0.3123,  0.3373,  0.8482, -0.7559,  1.5045,  1.2123],
         [ 1.9898, -1.9120,  0.2368, -0.5766, -1.0069, -0.7937],
         [ 0.4456, -0

In [37]:
import torch.nn as nn

fun = nn.Conv2d(3, 6, 3, 1)
fun1 = nn.Conv2d(3, 6, 3, 2)

In [38]:
fun(b)

tensor([[[ 1.6701e+00, -5.5540e-01, -1.2719e-01,  3.9989e-01],
         [-8.7836e-01, -3.2844e-01, -5.8949e-01, -5.5769e-01],
         [ 6.0707e-01, -1.4177e-01,  8.2436e-01, -8.0081e-01],
         [-1.5307e-01,  9.3665e-03, -1.1355e-01,  4.4346e-01]],

        [[ 3.7024e-01, -1.0707e+00, -6.0294e-01, -5.8213e-01],
         [ 9.5123e-01, -1.9341e-01, -6.5056e-01,  5.5600e-01],
         [-3.7530e-01, -4.3009e-01, -5.4045e-01, -5.5645e-01],
         [-6.6050e-01, -1.7853e-01,  6.8437e-04, -6.1150e-01]],

        [[ 4.2240e-01, -3.2046e-01,  1.4178e-01,  4.8284e-01],
         [ 4.7175e-01, -3.1553e-01, -1.1119e-01,  3.7410e-01],
         [-2.6753e-01, -4.4416e-01, -1.9671e-03,  4.2142e-01],
         [-2.7950e-01, -2.5928e-01, -2.2404e-01, -4.5181e-01]],

        [[ 3.9087e-01, -2.2596e-01, -8.6565e-03,  8.3414e-02],
         [-6.3179e-01,  4.4468e-01, -1.5845e-01,  4.4473e-01],
         [ 3.9522e-01, -6.7766e-01,  4.2840e-01,  6.8279e-01],
         [ 3.3941e-01, -3.9308e-01, -1.5915e-01, 

In [42]:
fun(b).shape

torch.Size([6, 4, 4])

In [43]:
fun1(b)

tensor([[[-1.1344, -0.2946],
         [ 0.1557,  0.0060]],

        [[ 0.4203,  0.0052],
         [ 0.5745,  0.5775]],

        [[ 0.1252, -0.3403],
         [ 0.6497, -0.4302]],

        [[-0.1013, -0.3383],
         [-1.1744, -0.0360]],

        [[ 0.8016,  0.2143],
         [-0.0135, -0.5071]],

        [[-1.5284, -0.7817],
         [ 0.7473,  0.0701]]], grad_fn=<SqueezeBackward1>)

In [44]:
fun1(b).shape

torch.Size([6, 2, 2])